# spring.application.name=microservice-gateway
# La seguridad de los microservicios se debe de manejar
# en api gateway / microservice-gateway
# server:
#   port: 8080

spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888
#   cloud:
#     gateway:
#       discovery:
#         locator:
#           enabled: true
#       routes:
#         - id: student
#           uri: http://localhost:8090
#           predicates:
#             - Path=/api/student/**
#         - id: course
#           uri: http://localhost:9090
#           predicates:
#             - Path=/api/course/**

# eureka:
#   instance:
#     hostname: localhost
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka
